<?php include('inc/doc.php'); ?>
<body id="about-us"> 
<?php include('inc/header.php'); ?>
      <img src="img/about-us-img.jpg" alt="" />
      <h3>About Us</h3>
      <p>Bond Plywood is a wholesale distributor of wood and laminated products servicing the woodworking industry throughout Southeast Michigan and Northwest Ohio.  Our customers are kitchen and bath manufacturers, furniture makers, architectural and commercial millwork houses, store fixture manufactures, countertop fabricators and lumber dealers.</p><img src="img/about-us-988.jpg" width="550" height="415" alt=""/>
      <p>Bond Plywood distributes some of the best products from the leading manufacturers in the woodworking industry. This list includes Panolam Surface Systems (<a href="pionite-laminates.php">Pionite</a>,<a href="panolam-melamine.php"> Panolam TFL</a></u>, <a href="frp-frl.php">FRL</a>), Valspar (<a href="valspar.php">wood coatings</a>), HI-MACS (<a href="hi-macs.php">solid surface</a>), Uniboard (<a href="http://www.bondply.com/particleboard-mdf.php">particleboard and MDF</a>), States Industries (<a href="http://www.bondply.com/plywood-veneer.php">hardwood plywood</a>), Brookside Veneers (veneer), Boise-Cascade (<a href="http://www.bondply.com/particleboard-mdf.php">particleboard</a>), Georgia-Pacific (<a href="http://www.bondply.com/particleboard-mdf.php">Particleboard and MDF</a>), Rehau (<a href="http://www.bondply.com/edgebanding.php">edgebanding</a> and <a href="http://www.bondply.com/adhesives-caulk.php">adhesives</a>), JB Cutting (<a href="http://www.bondply.com/cabinet-doors.php">thermofoil doors</a>), Valley Custom Door (<a href="http://www.bondply.com/cabinet-doors.php">wood doors</a>), Hettich (<a href="fasteners-slides.php">cabinet hardware</a>) and US Futaba (<a href="fasteners-slides.php">cabinet hardware</a>).&nbsp; We manufacture <a href="http://www.bondply.com/ultraclad.php">UltraClad</a>, which is a hot melt foil laminated to particleboard or MDF. In addition, we sell wood veneer, contact adhesives, caulk, fasteners and slides that compliment our product line. </p>
      <p>As the woodworking industry changes and evolves, our company's philosophy has not.  With a knowledgeable staff, it is our goal to give you the best possible service on a great selection of quality products at competitive prices. </p>
    </div>
    <?php include('inc/about-us-subnav.php'); ?>
    <?php include('inc/footer.php'); ?>
